FROM alpine:3.15.0
LABEL version="1.0.0" maintainer="Kousseila OUAGUENI" os="ubuntu"
ENV CONTAINER_USER="kousseila"
RUN adduser -D $CONTAINER_USER
USER $CONTAINNER_USER
CMD ECHO "hello-alpine, I'm ,"$CONTAINER_USER" and this is a container from my first image"
